### ISSUE TITLE
New term request: terms for taxonomic inventory metadata

### ISSUE THREAD

**Issue by tucotuco** [tucotuco/bco#1]
The following terms have been moved from the test file bco_taxonomic_inventory.owl into the main bco.owl file:

taxonomic inventory (BCO:0000048) > information content entity
taxonomic inventory process (BCO:0000047) > assay
adventitious taxonomic inventory process (BCO:0000055) > taxonomic inventory process 
capture taxonomic inventory process (BCO:0000054) > taxonomic inventory process 
compilation taxonomic inventory process (BCO:0000056) > taxonomic inventory process 
open search taxonomic inventory process (BCO:0000052) > taxonomic inventory process 
opportunistic search taxonomic inventory process (BCO:0000053) > taxonomic inventory process 
restricted search taxonomic inventory process (BCO:0000051) > taxonomic inventory process 

Suggested definition: see definitions in ontology file. 

Suggested reference:
Taxonomic Inventory Metadata Workshop

Additional comments:

These terms and definitions were created during a workshop at Yale in May 2013, as part of a minimum set of metadata terms for describing taxonomic inventories. Once the publication is ready, it should be added as a reference to these terms.

The primary term names given here are consistent with BCO and OBO Foundry naming policies. Where other names were used in the Taxonomic Inventory Metadata Workshop, these have been added as alternative terms using the annotation property "taxonomic inventory metadata preferred name".

**Comment by robgur** [comment]
Reviewed and we are good.
