### ISSUE TITLE
Resolve - Logical definition of Occurrence

### ISSUE THREAD

**Issue by tucotuco** [tucotuco/bco#18]
The spirit of Occurrence in Darwin Core is the evidence resulting from an Event. Thus, specimens (PreservedSpecimen, FossilSpecimen, LivingSpecimen), material samples (MaterialSample), and observations (HumanObservation, MachineObservation) are evidence resulting from "specimen collection", "material sampling process", or "observing process".

Depends on the logical definition of MaterialSample with respect to the types of specimens listed above (see https://github.com/tucotuco/bco/issues/17).

**Comment by rlwalls2008** [comment]
Some notes of our discussion of this are available at https://docs.google.com/document/d/131C2qS_BVvE1zUtbaoS2Mq8QWuJ9N5JR7RcShxgGA24/edit.  
Highlights include:
-the distinction between evidence and trust/confidence
-the importance of using evidence codes, so user can evaluate evidence
-current confounding of an occurrence of an organism in nature and the event of observing or sampling that organism

The decision was that we do not need to model dwc:Occurrence in BCO right now for our data needs, and given the confusion surrounding Occurrence, it would be better if we don't. Will add a comment to that effect.

**Comment by rlwalls2008** [comment]
I added an editor note:
This Darwin Core class should not be used when annotating data with BCO.  It is not mapped to BCO classes because its meaning is too ambiguous.
