### ISSUE TITLE
New term request: museum

### ISSUE THREAD

**Issue by tucotuco** [tucotuco/bco#2]
Term name: museum

Suggested parent term: OBI:organization

Suggested definition: An institution that cares for (conserves) a collection of artifacts and other objects of scientific, artistic, cultural, or historical importance and makes them available for public viewing through exhibits that may be permanent or temporary. 

Suggested reference:
Edward Porter Alexander, Mary Alexander; Alexander, Mary; Alexander, Edward Porter (2007-09). Museums in motion: an introduction to the history and functions of museums. Rowman & Littlefield, 2008. ISBN 978-0-7591-0509-6.

Copied from Wikipedia. Need to check reference.

May also want to add a term for natural history museum. Defined as above, but only for objects of scientific importance.

**Comment by robgur** [comment]
minor edits and iterated term to 'curated' status.

**Comment by tucotuco** [comment]
Closing, but see Issue #45.
