### ISSUE TITLE
Document changes to OBI imports

### ISSUE THREAD

**Issue by tucotuco** [tucotuco/bco#22]
Document this process....

update OBI imports (Rob and Ramona)

Open OBI_Ontofox.txt
Submit to Ontofox as is. Compare results with current file obi_bco_imports.owl to see what we have changed and what has changed in OBI.
Edit OBI_Ontofox.txt as needed.
Rerun through Ontofox.
Once import file is as it should be, change IRIs, etc. 
Commit new import file
Check that it imports properly in BCO by opening BCO from URL (this won’t work until we update the IRIs to github)

Will need to get rid of BFO has participant and participates in and specify that OBI relations are subproperties of corresponding RO classes. This must be done manually. Add comment to OBI ontofox file.
Check if this affects derivation relations (run reasoner).

**Comment by ramonawalls** [comment]
The reference made during commit fbacff71208ca0d65f689e47a7417f31f33fa0ff was a mistake.
