### ISSUE TITLE
machine observation process has wrong output

### ISSUE THREAD

**Issue by tucotuco** [tucotuco/bco#26]
It currently 'has output' some HumanObservation. This should be 'has output' some MachineObservation.

**Comment by rlwalls2008** [comment]
Use RO_0002234 (= has output) to specify this axiom. When we fix the RO import, it will work.

**Comment by rlwalls2008** [comment]
I have added temporary labels to these properties to make them easier to work with.

**Comment by tucotuco** [comment]
Resolved in 1cbcf76732372f9d652709be40145f571f1693df. Please check.
