### ISSUE TITLE
OBO terms reference old Google Code site for BCO

### ISSUE THREAD

**Issue by tucotuco** [tucotuco/bco#29]
The PURLs for BCO terms seem to be forwarding to the Google Code site rather than Github. http://purl.obolibrary.org/obo/BCO_0000051

**Comment by rlwalls2008** [comment]
Individual term IRIs should be forwarding to Ontobee, while the ontology purl should still be redirecting to Google Code, because we have not yet produced a stable release on github. I will check on the redirects.

**Comment by rlwalls2008** [comment]
This should be fixed as part of the release process.

**Comment by tucotuco** [comment]
As of right now

http://purl.obolibrary.org/obo/BCO_0000051

forwards to 

http://bco.googlecode.com/git/about/BCO_0000051

which does not exist.

**Comment by cmungall** [comment]
You need to set up

  /obo/bco/about/

as a partial redirect in OCLC

**Comment by rlwalls2008** [comment]
Partial redirect was fixed, so http://purl.obolibrary.org/obo/BCO_0000051 redirects to https://raw.githubusercontent.com/tucotuco/bco/master/about/BCO_0000051, but as Chris pointed out, we need to set up redirect for obo/bco/about.

**Comment by tucotuco** [comment]
How does one set up a redirect in OCLC? This is new to me.

**Comment by rlwalls2008** [comment]
Done.

/obo/bco/about/ redirects to http://www.ontobee.org/browser/rdf.php?o=BCO&iri=http://purl.obolibrary.org/obo/

**Comment by rlwalls2008** [comment]
OCLC is just purl.org. I think what happens is that the OBO Foundry has a redirect to lead http://purl.obolibrary.org/obo/BCO_0000051 to http://purl.obolibrary.org/obo/bco/about/BCO_0000051. Then I set up a partial redirect in purl.org to lead http://purl.obolibrary.org/obo/bco/about/BCO_0000051 to  http://www.ontobee.org/browser/rdf.php?o=BCO&iri=http://purl.obolibrary.org/obo/BCO_0000051.

http://www.oclc.org/research/themes/data-science/purl.html?urlm=168905

**Comment by tucotuco** [comment]
OK, good. That was the missing piece of information and it makes sense.
