### ISSUE TITLE
RO import

### ISSUE THREAD

**Issue by tucotuco** [tucotuco/bco#33]
Create a script to import RO object properties for making a module for RO rather than creating this by removing unneeded terms from RO manually.

**Comment by robgur** [comment]
Once there is a purl of the stable ro-eco.owl subset, we can point to that.  As interim solution, we can take the development version and use that.

**Comment by robgur** [comment]
PURL is here: https://obo-relations.googlecode.com/svn/trunk/src/ontology/subsets/ro-eco.owl

**Comment by robgur** [comment]
We also need to import http://purl.obolibrary.org/obo/ro/core.owl

**Comment by rlwalls2008** [comment]
ro-eco that we need is not yet being built. We will need to wait for that.

**Comment by rlwalls2008** [comment]
We don't really need the ro-eco subset at this point, and can get by with just ro-core. I will stop importing ro-eco.owl for now.

**Comment by rlwalls2008** [comment]
We don't need the eco-subset relations at this point, so I am just importing ro core.
