### ISSUE TITLE
Creator is capitalized in BCO

### ISSUE THREAD

**Issue by robgur** [tucotuco/bco#39]
looks into why "Creator" label is capitalized in BCO.

**Comment by robgur** [comment]
looks into why "Creator" label is capitalized in BCO.

**Comment by rlwalls2008** [comment]
Need to figure out where it is being imported from and make sure it is only coming in once. We could create a BCO specific label that is not capitalized, but I don't think it is very important for an annotation property.

**Comment by tucotuco** [comment]
OBI did this specifically. It is in obi_bco_imports.owl:

https://github.com/tucotuco/bco/blob/master/src/ontology/obi_bco_imports.owl#L349

###  http://purl.org/dc/elements/1.1/creator

dc:creator rdf:type owl:AnnotationProperty ;
           
           rdfs:label "Creator" ,
                      "Creator"@en-us ;
           
           rdfs:isDefinedBy dc: .

They did it with Contributor, Date, Description, Format, Subject, and Title as well. The originals are all lower case.

**Comment by tucotuco** [comment]
Comes from Dublin Core. Forget about it.
