### ISSUE TITLE
RO_00002560 and RO_0002561 need to be updated in RO

### ISSUE THREAD

**Issue by robgur** [tucotuco/bco#40]
These two terms are being imported from ro_eco subset without annotations.  They aren't currently being used in BCO.

**Comment by rlwalls2008** [comment]
Actually, the issue is that the full eco-subset is not built yet. Once it is ready, these relations will be imported automatically.

**Comment by rlwalls2008** [comment]
These are annotation properties that are included in the eco subset. We don't need them for now, so I am closing this issue.

**Comment by rlwalls2008** [comment]
I think this was supposed to be RO_0002352 and RO_0002353. In any case, the issue is solved by importing RO core.
