### ISSUE TITLE
observations in BCO

### ISSUE THREAD

**Issue by rlwalls2008** [tucotuco/bco#48]
Before we can define dwc:Occurence in BCO, we need to agree on the superclass of HumanObservation and MachineObservation. While we are at it, we should address more generally the classes for observations, with consideration to how they will map to OBOE and O&M.

**Comment by rlwalls2008** [comment]
OBOE was designed (as far as I understand) to deal with data that results from observations in a broad sense, that is, any process that yields an OBOE:Measurement (which is similar to IAO:data item). After some discussion at last week's mapping workshop, we tentatively agreed that OBOE:Observation maps to OML:Observation, which is a subclass of PROV:activity, and to OBI:assay, which is a subclass of process. Likewise, we tentatively agreed that OBOE:Measurement maps closely (if not exactly) to IAO:data item. The challenge here is that OBOE did not originally specify whether both Observation and Measurement were processes or information content entities, and preferred to leave them having a dual nature.

**Comment by robgur** [comment]
An issue for out papers but not one we need to sort for a BCO release, right?

**Comment by tucotuco** [comment]
Can we commit to the most specific class that makes sense (not dual nature)
and let OBOE sort it out for themselves?

**Comment by rlwalls2008** [comment]
Right, to both of you. Sorry I kind of left this half done. The point of this issue is that we need to get the BCO classes for observation in before the release, so we can map the dwc classes. Probably should have made this two separate issues, but I was thinking wholistically :)

**Comment by rlwalls2008** [comment]
Removing the OBOE mapping part from this issue.

**Comment by rlwalls2008** [comment]
I suggest that we make observing process a subclass of planned process, rather than just process.

**Comment by rlwalls2008** [comment]
Notes from call on 2015-03-20 at https://docs.google.com/document/d/131C2qS_BVvE1zUtbaoS2Mq8QWuJ9N5JR7RcShxgGA24/edit.

Decisions:
make bco:observing process subclass of planned process
add comment that we are coordinating with OBI to decide how this should relate to assay (equivalent class, subclass, superclass)
remove part of (which should have been has part anyway) selecting process. This is sort of covered by being a planned process
Change output of observing process to data item instead of just HO or MO
Make HO and MO subclasses of data item
create OBI tracker about this - maybe set up joint call with OBI

**Comment by rlwalls2008** [comment]
Also need to update the examples of usage for observing process, because they just say things like "Observing butterflies during a transect walk.". Should say "Observing and recording the presence or absence of butterflies during a transect walk."

**Comment by rlwalls2008** [comment]
Note that we have human observing process and machine observing process as subclasses of observing process.

**Comment by rlwalls2008** [comment]
See https://sourceforge.net/p/obi/obi-terms/745/
