### ISSUE TITLE
make CARO:organism a subclass of material entity

### ISSUE THREAD

**Issue by rlwalls2008** [tucotuco/bco#51]
It is currently a subclass of BFO:entity, but in CARO, it is specified as a subclass of material entity.

Need to fix this in PCO, and then just import it from PCO along with class for dwc:Organism.

**Comment by robgur** [comment]
We are going to have both caro:organism and dwc:organism?  If so, do we need to establish some equivalency?

**Comment by tucotuco** [comment]
I don't think they are equivalent. We will have to establish axioms to say
that caro:organism is a subset of the things meant by dwc:organism, right?

**Comment by rlwalls2008** [comment]
Right, dwc:Organism and caro:organism are quite different. See also pco tracker: https://code.google.com/p/popcomm-ontology/issues/detail?id=13

**Comment by rlwalls2008** [comment]
For now just did this in BCO. Will work on PCO imports for next release.
