### ISSUE TITLE
Update references in old BCO releases to Github

### ISSUE THREAD

**Issue by tucotuco** [tucotuco/bco#57]
...from Google Code so that they function correctly.

**Comment by rlwalls2008** [comment]
The release from 2014-05-27 has all imports merged, so when the partial redirect was fixed at purl.org, it fixed this one. However, this was not the correct format to follow for a release.

**Comment by rlwalls2008** [comment]
The IRI of BFO 1.1 (http://www.ifomis/org/bfo/1.1) in the BCO release for 2013-10-01 no longer works. Changed it to https://raw.githubusercontent.com/IFOMIS/BFO/1.1.1/bfo.owl/

**Comment by rlwalls2008** [comment]
For the 2013 release, updated IRIs for obi_bco_imports.owl, ontology_metadata_bco_imports.owl, and ro_bco_imports.owl, and they import correctly, but if you look at the raw file for these, they still reference google code:
<rdf:RDF xmlns="http://bco.googlecode.com/git/src/ontology/iao_bco_imports.owl#"
xml:base="http://bco.googlecode.com/git/src/ontology/iao_bco_imports.owl"

**Comment by rlwalls2008** [comment]
Steps to fix 2013 imports:
1. Edit each (IAO, OBI, Ontology-metadata, RO)  import file to change IRI to http://purl.obolibrary.org/obo/bco/import.owl. 
2. Make sure version IRI is of the formhttp://purl.obolibrary.org/obo/bco/releases/2013-10-01/import.owl. Save and commit.
2. For IAO and OBI imports, hand edit ontology file to change reference to google code to purl. Save each ontology and commit.
3. For each import file, while in bco-non-classified.owl, remove (x out) current direct import and re-import from purl of the form http://purl.obolibrary.org/obo/bco/releases/2013-10-01/import.owl. Save bco-non-classified.owl and commit.

**Comment by rlwalls2008** [comment]
Note that this does not work for ontologies stored in src/ontology.
