### ISSUE TITLE
remove duplicate bco versions of darwin core class terms (fossil record, etc.)

### ISSUE THREAD

**Issue by rlwalls2008** [tucotuco/bco#6]
For each bco version of the darwin core term:
Add annotation boolean "deprecated" true - see fossil specimen

Add "has obsolence reason" (need single quotes when making term assignments if the term has spaces, but don’t use quotes when entering the name into the label annotation)

under entityIRI choose individuals choose "failed exploratory term"

remove curation status annotation

copy all other annotations (definition, comments) over to the dwc version
-note that terms can only have one comment. If necessary, add new comment after text of original DwC comment.

red x on subclass of X to remove it

add subclass of "Obsolete Class" to get it on the Obsolete Class list

**Comment by tucotuco** [comment]
Fully resolved with merge 33f5d501a8f2e6897ea1bdae784b1cfd18bbc6d0.
