### ISSUE TITLE
Finalize 2015-04-10 release

### ISSUE THREAD

**Issue by rlwalls2008** [tucotuco/bco#63]
Check that the purls all look okay, that the ontologies look as expected. Announce on bco-discuss.

**Comment by rlwalls2008** [comment]
Also close milestone, I guess.

**Comment by tucotuco** [comment]
Updated the wiki page https://github.com/tucotuco/bco/wiki/How-to-maintain-PURLs to show where the current release redirects to. Cleaned up the links to the Guide and Help on that page. Cleaned up the page https://github.com/tucotuco/bco/wiki/How-to-make-a-release for formatting and a few typos.

The release files all look good to me, but there is the remaining issue #29 for redirects that must be resolved. Made comment there.

**Comment by rlwalls2008** [comment]
Partial redirect to term IRIs is done. Issue #29 is closed.
