### ISSUE TITLE
BCO terms have small letters in ids

### ISSUE THREAD

**Issue by rlwalls2008** [tucotuco/bco#66]
and they should be capital letters

**Comment by rlwalls2008** [comment]
This will be fixed before moving to the new repo (#69). Must send an announcement to obo-discuss, in case anyone is using bco.

**Comment by rlwalls2008** [comment]
the following should be deprecated, to be replaced with external ontology term (mostly OBI):
bco_0000000 evidence role
bco_0000005 printed report
bco_0000007 selecting process
bco_0000021 physical extraction process

The following should be deprecate dand replace with a new term that has a BCO_ identifier:
bco_0000003 observing process
bco_0000006 printed observational report
bco_0000016 submitting process
bco_0000025 locality description
bco_0000031 museum collection
bco_0000032 organismal museum collection
bco_0000042 taxonomic identification process
bco_0000043 process that yields a material representation of a material entity
bco_0000044 material target of observation
bco_0000045 process that yields an information artifact that is a representation of a material entity
bco_0000046 material target of observation role

The rest of the terms are already deprecated.

**Comment by cmungall** [comment]
I'm hoping to implement this soon: 
https://github.com/ontodev/robot/issues/65

If you don't want to wait then Jim's plugin is useful here

**Comment by rlwalls2008** [comment]
Thank, Chris. I wanted to get this done before moving the repo (although it is not really necessary). Can you point me at Jim's plugin?

**Comment by rlwalls2008** [comment]
Deprecated with a comment to be replaced by external term (mostly OBI):
bco_0000000 evidence role
bco_0000005 printed report
bco_0000007 selecting process
bco_0000021 physical extraction process
bco_0000043 process that yields a material representation of a material entity
bco_0000045 process that yields an information artifact that is a representation of a material entity

Deprecated the following terms and replaced them with new terms that had BCO_ id: 
bco_0000003 observing process
bco_0000016 submitting process
bco_0000025 locality description
bco_0000031 museum collection
bco_0000032 organismal museum collection
bco_0000042 taxonomic identification process
bco_0000044 material target of observation
bco_0000046 material target of observation role

Terms that can't be fully replaced until I import a new parent class (deprecated for now, with comment):
bco_0000006 printed observational report
