### ISSUE TITLE
definition of taxonomic inventory

### ISSUE THREAD

**Issue by rlwalls2008** [tucotuco/bco#70]
In BCO, it is currently defined as "An information content entity that is a list of taxa recorded in some geospatially defined area over some stated time period using some method involving some actor." 

In the manuscript, it is defined as "A list of biological entities recorded over defined spatial and temporal scope following a described sampling protocol and sampling effort and addressing a specified organismal scope." 

Although  these are quite similar, I think there is more information in the manuscript definition, and it reads better.

New suggested definition for BCO:
An information content entity that is a list of biological entities recorded over some defined spatial and temporal scope following a described sampling protocol and sampling effort and addressing a specified organismal scope.

@robgur

**Comment by robgur** [comment]
Agree.  Shall I change the BCO definition?

**Comment by jdeck88** [comment]
In putting it into the context of an Information Content Entity it sounds
odd that it is directly talking about a list (or set?) of biological
entities.

The following clarifies it for me:

"An information content entity that is a list names ascribed to biological
entities recorded over some defined spatial and temporal scope following a
described sampling protocol and sampling effort and addressing a specified
organismal scope."

On Thu, Jan 21, 2016 at 2:54 PM, Rob <notifications@github.com> wrote:

> Agree. Shall I change the BCO definition?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tucotuco/bco/issues/70#issuecomment-173741797>.
>



-- 
John Deck
(541) 914-4739

**Comment by rlwalls2008** [comment]
Thanks, @jdeck88. I like that suggestion. I will update BCO accordingly, next time I work on it. @robgur, if you have time to make the change, please go ahead.
